### PR TITLE
Doubleclick in previews to trigger action

### PR DESCRIPTION
**Pull request by elmodor**
**Fixes/Solves**
While I was create an asset pack, I was adding cards to the game quite often. Clicking on the card an add is quite tedious after a while.
Also a double click on an item is usually an enter action in many games / GUIs.

So I tried to implement a double click action for these. The double click action now works for:
- Objects (to add)
- Games (to load)
- Room (to select, apply has to be hit manually still)
- Loading Savegames
- Saving Savegames

### CODE REVIEW

**Review by drwhut — APPROVED** [review]
Looks good, will test it thoroughly before merging!

**Review by drwhut — CHANGES_REQUESTED** [review]
I've just been testing the changes, and there's one thing that strikes out to me: when spamming double click on an object, the "selected" background flickers on and off. Is it ok if this stays on when spamming double-click? I think this is because single-click toggles whether the item is selected - this functionality can change if need be, since I've just realised that most file managers don't work this way (only when holding down Ctrl does it toggle).

**Comment by elmodor** [comment]
So I modified the click behavior. Singleclick does not unselect anymore. Only multi_select can unselect.
I think this looks more clean now too.

**Review by drwhut — APPROVED** [review]
Looks good! I'll test these changes again before merging.

**Pull request merged**
