### PR TITLE
Added an "All" filter for Packs and Types

### LINKED ISSUE #141: Add "all" asset pack option in selection menus.
**Is your feature request related to a problem? Please describe.**
If you have multiple asset packs installed and you want to load a game you have to select "Games" and then change "Pack" to the correct game and then load the savegame. I assume that custom packs will most likely consist of one game. 
Nevertheless the search feature is not useful because it only searches in the current pack.

**Describe the solution you'd like**
I want a Pack filter "All" which shows all saved games from all packs. 
Similar the Type could be adjusted to show all objects within a pack (or all packs if selected) and then the search function can be used properly and efficiently. (So maybe also the ability to do this for Objects)

The Pack: "All" should also be selected by default to show all available games.

### PR DESCRIPTION
**Pull request by elmodor**
**Fixes/Solves**
Fixes #141 

I thought about adding an "All" type to the AssetDB - but since this is an "UI" element only I don't think this belongs into the AssetDB.

The idea is that there is an "All" pack that displays all packs. This is available in all PreviewFilter instances and selected by default.

I also added an "All" filter for types. This is beneficial if you use the search function to filter. Or to see all assets in one go. Also selected by default.
There is an additional condition for types: the "All" filter will only be created if there is more than 1 type. So for instances like table, skybox etc there won't be an "All" type filter.

### CODE REVIEW

**Review by drwhut — CHANGES_REQUESTED** [review]
Thank you! The only changes that are necessary is to allow the "All" string to be translated (which propagates through some of the other checks).

**Review by drwhut — CHANGES_REQUESTED** [review]
One last suggestion: I think it may be worth having these meta strings as `const` at the top of the file, so they only need to be changed in one place.

Plus, *technically* someone could make an asset pack called "ALL_PACKS_DISPLAY", so it may be worth prepending a "@" to the string, or another special character that cannot be used in folder names.

**Comment by elmodor** [comment]
I can prepend an @ - but I guess you are talking about Windows here? On Linux, you can create a folder with any character. But I doubt someone names their pack "@ALL_PACKS_DISPLAY". Or we can prepend an @ for all other asset packs:
`_pack_button.set_item_metadata(_pack_button.get_item_count() - 1, "@" + pack)`

I will do the first option for now since I doubt anyone names there pack like this

**Review by drwhut — APPROVED** [review]
Looks good! Will test before merging.

**Comment by drwhut** [comment]
Ah, looks like one of the PRs created a merge conflict.

**Pull request merged**
