### PR TITLE
Added two simple cube tokens

### PR DESCRIPTION
**Pull request by elmodor**
**Fixes/Solves**
There were no cube tokens present in the default asset pack. This serves two purposes:
- Some default basic colored tokens (red and green). They can be used as counter, tracker, etc
- As an example template for other cube tokens

The focus is of course more on the first bullet point: To have a marker/tracker without any number on it that can be used universally.

Size measured by some real cardboard cut out tokens.

### CODE REVIEW

**Review by drwhut — CHANGES_REQUESTED** [review]
Thank you for the PR!

This seems like a good idea, but I've got two points:
- Instead of having different images for each token, it's probably better to have one image for a "white" token, and allow the user to change the colour in-game - you can also add some preset token colours using the config file, see the dice configs as an example!
- Unless you don't mind me being the "author" of the images, you can set the `author` and `license` of the images in the config file.

**Review by drwhut — CHANGES_REQUESTED** [review]
Cool, just a couple more things that I've spotted!

- If the image is just pure white, you can massively reduce the size of the image by having it be a 1x1 .bmp image!
- The "A simple token." description is redundant, since it gets overwritten by all of the other descriptions in the file.

**Comment by elmodor** [comment]
It's not completely pure white. I made the shade a tiny bit different. Would you rather like a pure white one?

Removed the redundant desc

**Comment by drwhut** [comment]
Ah sorry, I just assumed it was pure white. The original colour is fine! :slightly_smiling_face:

**Comment by elmodor** [comment]
Okay, let me know if there's anything else left to do :smile:

**Comment by drwhut** [comment]
Apart from the simplifying of the image, we could also take the time to add a whole bunch of colours? We could use the dice as an example (and that way, we could get the tokens and dice to match colours?)

**Comment by elmodor** [comment]
Will do. 

Is there any place (in the repo or in the docs) where we could store UV template files?

**Comment by elmodor** [comment]
White image is 1x1 bmp and added all the colors from the dices.

**Review by drwhut — APPROVED** [review]
Looks good!

**Comment by drwhut** [comment]
> Is there any place (in the repo or in the docs) where we could store UV template files?

There's already UV templates [in the docs](https://tabletop-club.readthedocs.io/en/latest/custom_assets/asset_packs/file_types.html#cube).

**Comment by elmodor** [comment]
Turns out many games also need: cubes. Like little cubes:
[Little cubes](https://cf.geekdo-images.com/camo/b2064567791b87217d04b670337f82549e65cfdd/687474703a2f2f696e737069726174696f6e746f7075626c69636174696f6e2e66696c65732e776f726470726573732e636f6d2f323031302f30382f7475622d6f2d63756265732e676966)

How would you feel if I extended this MR to include not only tokens but also cubes?
Changing the name for the tokens to: White Token and the cubes would be White Cube

**Comment by drwhut** [comment]
I feel like the tokens should do for most use cases - can always open up another PR if there's demand for little cubes!

**Pull request merged**
